---
app_name: teashop

# custom
ansible_user_name: ansible
ansible_user_password: "{{ lookup('file', lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_user_password') }}"
ansible_user_private_key: "{{ lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_ssh' }}"
ansible_user_public_key: "{{ lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_ssh.pub' }}"

# native
ansible_user: '{{ ansible_user_name }}'
ansible_become_password: '{{ ansible_user_password }}'
ansible_ssh_private_key_file: "{{ ansible_user_private_key }}"

# admin
admin_name: ivan
admin_password: "{{ lookup('file', lookup('env', 'PWD') ~ '/' ~ 'secrets/admin_password') }}"

# monitoring
zabbix_agent2_monitoring_server_ip: "{{ hostvars['monitoring.tea']['ansible_host'] }}"

# dockerhub_proxy
dockerhub_proxy_ip: "{{ hostvars[groups['dockerhub_proxy_server'][0]]['ansible_host'] }}"
