---
app_name: teashop

# custom
ansible_user_name: ansible
ansible_user_password: "{{ lookup('file', lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_user_password') }}"
ansible_user_public_key_file: "{{ lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_ssh.pub' }}"
ansible_user_private_key_file: "{{ lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_ssh' }}"
# native
ansible_become_password: '{{ ansible_user_password }}'
ansible_user: '{{ ansible_user_name }}'
private_key_file: "{{ lookup('env', 'PWD') ~ '/' ~ 'secrets/ansible_ssh' }}"

# admin
admin_name: ivan
admin_password: "{{ lookup('file', lookup('env', 'PWD') ~ '/' ~ 'secrets/admin_password') }}"

# monitoring
zabbix_agent2_monitoring_server_ip: "{{ hostvars['monitoring.tea']['ansible_host'] }}"
