---

security_ufw_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "3142" # apt cacher
  - "3141" # devpi server

security_ufw_allowed_udp_ports:
  - "68"
  - "67"

# nginx docker vars
nginx_docker_http_listen_port: 80
nginx_docker_container_name: nginx_load_balancer
nginx_docker_templates_subdir: gateway

# dhcp server vars
dhcp_srv_network_interface: "ens19"
dhcp_srv_ip_range_start: "192.168.56.100"
dhcp_srv_ip_range_end: "192.168.56.200"
dhcp_srv_ip_rent_hours: 24h
dhcp_srv_netmask: "255.255.255.0"
dhcp_srv_gateway: "{{ ansible_host }}"
dhcp_srv_dns_servers: "{{ ansible_host }}"

# apt cacher vars
apt_cacher_allow_http_tunnels: true

# devpi_server vars
devpi_server_password: "{{ lookup('file', lookup('env', 'PWD') ~ '/' ~ 'secrets/devpi_server_password') }}"
