

# hosts
gateway.tea ansible_host=192.168.56.1 CIDR=24

first.app.tea ansible_host=192.168.56.143
second.app.tea ansible_host=192.168.56.200

db.tea ansible_host=192.168.56.115

monitoring.tea ansible_host=192.168.56.21

devserver.tea ansible_host=192.168.56.142

# Groups
[gateway]
gateway.tea

[main_app_servers]
first.app.tea
second.app.tea

[database_server]
db.tea

[devserver]
devserver.tea

[apt_cacher]
gateway.tea

[devpi_server]
gateway.tea

[dockerhub_proxy_server]
gateway.tea

# childrens
#[hosts_with_nginx_docker:children]
#gateway
#main_app_servers

[hosts_with_docker:children]
gateway
main_app_servers

[hosts_with_zabbix_agents:children]
gateway
main_app_servers
database_server
