---
- name: Common servers preparation
  hosts: all
  roles:
    - common_server_prep

- name: install docker to hosts
  hosts: hosts_with_docker
  become: yes
  roles:
    - geerlingguy.docker

- name: Deploy Nginx Services in docker
  hosts: hosts_with_nginx_docker
  roles:
    - nginx_docker

- name: Install Zabbix Agents
  hosts: hosts_with_zabbix_agents
  roles:
    - zabbix_agent2

- name: install postgresql
  hosts: database_servers
  become: yes
  roles:
    - geerlingguy.postgresql

- name: Set up teashop Postgresql Database
  hosts: database_servers
  become: yes
  become_user: postgres
  roles:
    - app_database

- name: Set up security rules
  hosts: database_servers
  become: yes
  roles:
    - security