---
# mn - managed node

mn_cfg_base_dir: /home/ansible/hostcfg

templates_dir: '{{ role_path }}/templates/{{ templates_subdir }}'

mn_nginx_cfg: '{{ mn_cfg_base_dir }}/nginx'
mn_web_app: '{{ mn_cfg_base_dir }}/web_app'