---
- name: Deploy gateway
  hosts: gateway
  become: true
  roles:
    - common
    - security

    - apt_cacher
    - apt_proxy

    - geerlingguy.docker

    - devpi_server

    - zabbix_agent2
    - dhcp_srv

