---
- name: Zabbix agent 2 install release package
  become: true
  ansible.builtin.apt:
    deb: "{{ zabbix_agent2_repo_url }}"

- name: Zabbix agent 2 install
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: zabbix-agent2
    state: present

- name: Zabbix agent 2 deliver config
  ansible.builtin.blockinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    create: true
    owner: root
    group: root
    mode: "0644"
    append_newline: true
    prepend_newline: true
    block: "{{ lookup('template', 'zabbix_agent2.conf.j2') }}"
  notify: Zabbix agent 2 restart

- name: Zabbix agent 2 Restart and enable service zabbix-agent2
  become: true
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
  changed_when: false
