---
- name: install zabbix release package
  become: yes
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian{{ ansible_facts['distribution_major_version'] }}_all.deb"

- name: install zabbix agent 2
  become: yes
  ansible.builtin.apt:
    update_cache: true
    name: zabbix-agent2
    state: present

- name: deploy zabbix zabbix_agent2.conf
  become: true
  ansible.builtin.template:
    src: zabbix_agent2.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart and enable service zabbix-agent2
  become: yes
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: yes