---
- name: Install common packets, postgresql, set up security
  hosts: database_servers
  roles:
    - apt_proxy
    - common
    - security

    - geerlingguy.postgresql

    - zabbix_agent2

    - app_db
