---
- name: Deploy_apps
  hosts: main_app_servers
  tasks:
    - include_role:
        name: '{{ item }}'
      loop:
        - apt_proxy
        - common
        - security
        - geerlingguy.docker
        - zabbix_agent2

    - include_role:
        name: dockerhub_proxy
        tasks_from: client
