---
- name: Run devpi under docker
  community.docker.docker_container:
    name: devpi_server
    image: 'jonasal/devpi-server:latest'
    state: started
    restart_policy: unless-stopped
    ports:
      - "3141:3141"
    env:
      DEVPI_PASSWORD: "{{ devpi_server_password }}"
