---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_reboot_required_file

- name: Finding out if reboot is required
  ansible.builtin.reboot:
    msg: "!!! rebooting !!!"
  when: common_reboot_required_file.stat.exists

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages_list }}"
    state: present
    update_cache: true
