---

- include_tasks: server_conf.yml

- name: Drop if app db presents
  become: true
  become_user: postgres
  block:
    - name: Collect all databases
      community.postgresql.postgresql_info:
        filter:
          - "databases"
      register: app_db_dblist

    - name: Check if db is present
      ansible.builtin.pause:
        prompt: |-
          WARNING: APP DATABASE {{ app_db_main_db }} IS PRESENT
          SCRIPT FOR SETTING DB AND ITS TABLES
          WILL NOT BE EXECUTED
      when: "app_db_main_db in app_db_dblist.databases"
      register: app_db_present

- name: Create db and set up tables
  become: true
  become_user: postgres
  when: app_db_present is skipped
  block:
    - name: Create DB {{ app_db_main_db }}
      community.postgresql.postgresql_db:
        name: "{{ app_db_main_db }}"
        comment: main database of app {{ app_db_main_db }}

    - name: Copy set_up_database.sql to host
      become: true
      become_user: root
      ansible.builtin.copy:
        src: "{{ app_db_set_up_script_path }}"
        dest: "/tmp/script.sql"
        owner: postgres
        group: postgres
        mode: "0600"

    - name: Run set_up_database.sql
      community.postgresql.postgresql_script:
        login_db: "{{ app_db_main_db }}"
        path: /tmp/script.sql

    - name: Create user of this db and make him owner of database {{ app_db_main_db }}
      community.postgresql.postgresql_query:
        login_db: "{{ app_db_main_db }}"
        query: >-
          CREATE ROLE {{ app_db_superuser_role }} WITH SUPERUSER LOGIN PASSWORD '{{ app_db_superuser_pass }}';
          ALTER DATABASE {{ app_db_main_db }} OWNER TO {{ app_db_superuser_role }};
