---
- name: Deploy gateway
  hosts: gateway
  roles:
    - apt_cacher
    - apt_proxy

    - common_server_prep
    - security

    - geerlingguy.docker

    - zabbix_agent2
    - DHCP_srv
    - nginx_docker
