---
- name: deploy_apps
  hosts: main_app_servers
  roles:
    - common_server_prep
    - geerlingguy.docker
    - zabbix_agent2
    - security

- name: deploy nginx conf
  hosts: main_app_servers
  become: no
  roles:
    - nginx_docker
