---
- import_tasks: validate_cfg_in_local.yml

- import_tasks: deliver_cfg.yml
  notify: Restart nginx container

- name: Ensure Nginx container is running
  community.docker.docker_container:
    name: "{{ nginx_docker_container_name }}"
    image: "nginx:latest"
    state: started
    restart_policy: always
    volumes:
      - "{{ nginx_docker_nginx_cfg }}/conf.d:/etc/nginx/conf.d:ro"
      - "{{ nginx_docker_nginx_cfg }}/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "{{ (nginx_docker_web_app ~ ':/var/www/html:ro') if nginx_docker_has_web_app == true else ('/dev/null:/dev/null:ro') }}"
    published_ports:
      - "{{ nginx_docker_http_listen_port }}:80"
  notify: Restart nginx container
