---
- name: Create temporary build directory for config validation
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: nginx_docker_tmp_dir
  changed_when: false

- name: Create dirs with everything from templates
  ansible.builtin.file:
    path: "{{ nginx_docker_tmp_dir.path }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ nginx_docker_templates_subdir }}"
  when: item.state == 'directory'
  changed_when: false

- name: Templating cfgs to testing dir
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nginx_docker_tmp_dir.path }}/{{ item.path | splitext | first }}" # also removes .j2
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ nginx_docker_templates_subdir }}"
  when: item.state == 'file'
  changed_when: false

- name: Validate nginx conf
  ansible.builtin.command:
    cmd: >
      docker run --rm -t
      -v "{{ nginx_docker_tmp_dir.path }}/conf.d/:/etc/nginx/conf.d/:ro"
      -v "{{ nginx_docker_tmp_dir.path }}/sites-enabled/:/etc/nginx/sites-enabled/:ro"
      nginx:latest nginx -t
  changed_when: false
